# Generated by Django 2.2.6 on 2019-11-03 20:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('user_name', models.CharField(max_length=37)),
                ('email', models.EmailField(max_length=254)),
                ('created_at', models.DateTimeField(verbose_name='Created At')),
            ],
        ),
    ]
