# Generated by Django 3.0.1 on 2019-12-21 07:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_auto_20191103_2219'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User',
        ),
    ]
